name: Checkmarx Debug SARIF
on:
  push:
    branches:
      - master

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Checkmarx One CLI Action
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: anjali-sarif
          cx_tenant: cx_seg
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: >
            --debug 
            --report-format sarif
            --output-path cx_result.sarif
            --scs-repo-url https://github.com/WebGoat/WebGoat
            --scs-repo-token ${{ secrets.GIT_PUSH_TOKEN }}
            --sca-exploitable-path true
            

      - name: Upload XML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cx_result.sarif
          path: cx_result.sarif
      - name: Upload Checkmarx SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif