name: Test

on:
  push:
    branches:
      - master

jobs:
  test-cli:
   name: Test
   runs-on: ubuntu-latest
   env:
     GOMAXPROCS: 32

   steps:
     - name: Checkout
       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

     - name:  Install Checkmarx CLI
       run: |
         curl -LO https://github.com/Checkmarx/ast-cli/releases/download/2.3.29/ast-cli_2.3.29_linux_x64.tar.gz
         tar -xvzf ast-cli_2.3.29_linux_x64.tar.gz
         chmod +x ./cx
         sudo mv ./cx /usr/local/bin/cx
         
     - name: Repeat configuration
       run: |
         for i in {1..200}; do
         (
         cx configure set --prop-name cx_base_uri --prop-value "dummy_url_$i" &
         CX_PID=$!
         sleep 0.05
         kill -USR1 $CX_PID 2>/dev/null || echo "Process $CX_PID already exited"
         wait $CX_PID
         )&
          done
          wait
          echo "Stress test completed. Check error.log for any crashes."

